//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oblig4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int roomnumber { get; set; }
        public string size { get; set; }
        public Nullable<int> numberofbeds { get; set; }
        public Nullable<int> price { get; set; }
    }
}
